### ISSUE TITLE
New RedirectInstance() crashes on Excel 2016 32 bit

### ISSUE THREAD

**Issue by MarioAnthes** [cristianbuse/VBA-MemoryTools#11]
Hi Cristian,
I've tried to run DemoMain() in VBA MemoryTools_Demo.xlsm. It works fine in Excel 2016 VBA 64 bit, but the 32 bit version crashes in sub RedirectInstance(). Your previous version of RedirectInstance() in LibMemory (prior to 24-Nov-2023) was running without problems in Excel VBA 32 bit.

**Comment by cristianbuse** [comment]
Hi @MarioAnthes ,

Thank you for raising the issue!

Before I pushed the new version, I did testing for Win x64 VBA7, Mac x64 VBA7 and Win x32 VBA6. However, I did not test on Win x32 VBA7 and I completely missed this issue which was a memory alignment problem that was indeed addressed in the previous version. This [last commit](https://github.com/cristianbuse/VBA-MemoryTools/commit/2a7cc539c60550639e442c3a88a08662a3b7bc31) fixes the issue.

Many thanks!
