### ISSUE TITLE
RedirectInstance raises error 5 when funcReturn is a class object

### ISSUE THREAD

**Issue by MarioAnthes** [cristianbuse/VBA-MemoryTools#12]
Hi Cristian, while testing I came across another issue with the new implementation of RedirectInstance:

If function Init() in DemoClass returns DemoClass instead of Object, RedirectInstance raises error 5 due to swapAddress = NULL_PTR
```
Public Function Factory(ByVal newID As Long) As DemoClass
    Dim c As New DemoClass
    Set Factory = Init(c, newID)
End Function

Private Function Init(ByVal c As DemoClass, ByVal newID As Long) As DemoClass
    RedirectInstance Init, Me, c
    m_id = newID
    Set Init = Me   ' or Set Init = c
End Function
```
The same scenario used to work with the previous implementation of RedirectInstance.

Btw, many thanks for your incredible work. LibMemory raises VB(A) to the next level.

**Comment by cristianbuse** [comment]
Thanks again @MarioAnthes  for the input!

The last commit should fix the issue. I had to drop support for User Defined Types but I guess that is a very narrow use. Any type of class return should work now, including IUnknown (vbDataObject).

And many thanks for the kind words - glad this library is of use.
