### ISSUE TITLE
Did you know, `RtlMoveMemory` speed changes dependent on trust center settings?

### ISSUE THREAD

**Issue by sancarn** [cristianbuse/VBA-MemoryTools#14]
> Copying a byte for 10,000 times on Windows with VBA7 x64 using RtlMoveMemory API takes around 10 seconds while the native struct approach takes only around 8 milliseconds for the same number of iterations. So, the speed gain is over 1000x in some cases.

@cristianbuse recently found out that this may be a trust center issue. If I add the workbook path to the trust center as a trusted location, there is a huge boost in macro speed. So as an alternative to using a totally different mechanism for `CopyMemory` an option is to add the path (or the root including subfolders) as a trusted location, and closing/re-opening the workbook.

![image](https://github.com/cristianbuse/VBA-MemoryTools/assets/7938900/ce3dc6e5-3a0c-4d4f-a4ed-3f40d2524f0b)

![image](https://github.com/cristianbuse/VBA-MemoryTools/assets/7938900/969e79f6-bbff-4448-8ae0-ac63aa4e1bb3)

Note: adding the location to trustcenter also increases performance of various generic VBA operations (not totally sure which... but think form repaint is one of them) .

**Comment by cristianbuse** [comment]
Thanks @sancarn ,

Yes, I know. You can try an API call in a new file (unsaved) and you still get the speed gain until you save and reopen.
Same with Enabling all macros by default and after a restart of the application.

However, you only get a partial speed gain compared to what it can do in VBA6 and it's basically still orders of magnitude better to use LibMemory. Unfortunate

**Comment by sancarn** [comment]
Ah, good to know 👍  Thanks for the info :)
