### ISSUE TITLE
Reduce conditional compilation

### ISSUE THREAD

**Issue by Greedquest** [cristianbuse/VBA-MemoryTools#3]
```vba
#If VBA7 = 0 Then
	Public Enum LongPtr
		[_]
	End Enum
#End If
```

I discovered this trick recently - Alias LongPtr to Enum/Long on systems without LongPtr. `?TypeName(x As LongPtr) -> "Long"`

Would get rid of many of your `#If VBA7` blocks (and the `#If Win64` in some cases), and provide LongPtr (basically) in VBA6 hosts that reference your project.

**Comment by cristianbuse** [comment]
Wow. Cool. I am a bit busy these days but I will update the repository as soon as I get the chance using your new trick. Thank you! Will of course add your name next to it along with the issue link. 

How on earth did you find this one? :)

Cheers

**Comment by Greedquest** [comment]
> How on earth did you find this one? :)

Staring at the screen until something clicked, although I think I might have seen it somewhere before. Have been reviewing some code for calling private members of modules using the hidden ITypeInfo, lots of pointers involved.

**Comment by cristianbuse** [comment]
Hi @Greedquest,

I just had a chance to install Office 2007 and run some tests in VBA6. This trick you discovered works really well with 2 exceptions that I found:  
 1. A constant cannot be declared using an Enum. A ```#If VBA7``` is still required. This is absolutely not an issue as it's quite rare one would need a ```LongPtr``` constant and anyway easy to do with conditional compilation
 2.  If the ```LongPtr``` Enum is declared ```Public``` in separate modules then it becomes an 'ambiguous' compilation error. This could happen when using standalone library-like modules that all expose functions returning ```LongPtr```

Do you have any ideas on how to work around the second issue?

BTW, I cannot believe how fast is the CopyMemory API in VBA6. Mental. I think they ruined something when they introduced the ```PtrSafe``` notation. Something is seriously wrong with all APIs speed in VBA7.

**Comment by Greedquest** [comment]
So you mean like if multiple modules declare the enum then VBA is unhappy about ambiguity?

 Well TBH I use your memory tools library as an Excel addin (xlam). I believe if you have multiple library addins then redefining LongPtr once per library won't matter as VBA references are resolved in order (in the references pane, top to bottom) so there is no ambiguity. What you're seeing would be a problem for any public names defined in more than one module of the same project? That's part of the reason I use addins; each project gets its own namespace so names can be repeated, and project hierarchy resolution or fully qualified member calls disambiguate the options.

I don't think there's something like `#ifndef` to avoid repeat declarations within the same project unfortunately.

The const thing is a bit annoying yes, and is a non-obvious bug if you develop in VBA7 with no complaints then it doesn't work on VBA6. However I think a bigger source of bugs is duplicating large chunks of code and forgetting to update one when you update the other (i.e the `#If VBA7` block gets out of sync with the `#Else` block during development), so I think this is a tradeoff I would be happy with. Plus if all your VBA6 compatible code still says `LongPtr` I think it is self documenting. It is  similar to how I declare HRESULT return codes as an enum rather than Long.

**Comment by Greedquest** [comment]
In surprised PutMem4/GetMem4 were slow for you. In principle, they are each only one or two assembly instructions in the compiled dll. I haven't got round to re profiling but maybe something to double check?

**Comment by Greedquest** [comment]
> I use addins; each project gets its own namespace so names can be repeated

As mentioned in a few places, I'm working on a VBA package manager written in python that strongly encourages the use of addins (Access & Excel only) as the default way to share and distribute libraries (and makes constructing them much easier). I have no idea what the repercussions of this will be, as I have relatively little experience with actual large scale VBA development and nobody seems to have an addin based network of libraries, perhaps VBE will have some arbitrary limit I am not yet aware of. Do you have any thoughts on that?

**Comment by cristianbuse** [comment]
> So you mean like if multiple modules declare the enum then VBA is unhappy about ambiguity?

Yes. Unfortunately, using add-ins is not an option for me as some files (Excel) are sent to clients (by my company). They must work as stand-alone Excel files with no extra dependencies. So, I structure my libraries as either one standard module or the minimum combination of standard/modules classes. Hence, all the stuff I've posted on GitHub or CR are like that.  Some of those files that we send to clients are over 100+ code modules and over 60k lines of code. Yeah, I know. Nothing I can do about it.

> In surprised PutMem4/GetMem4 were slow for you. In principle, they are each only one or two assembly instructions in the compiled dll. I haven't got round to re profiling but maybe something to double check?

You've probably seen [this CR post](https://codereview.stackexchange.com/questions/270258/evaluate-performance-of-dll-calls-from-vba) but just in case I've added the link. His image:  ![table](https://raw.githubusercontent.com/pchemguy/SQLiteC-for-VBA/develop/Assets/Diagrams/VBA%20Performance.png) points out the issue.

API speed seems to be a VBA7 issue. API speed in VBA6 seems normal/fast. I should probably update this repository to take that into account (as I already do for Mac) and basically do the ByRef logic only on Win and VBA7.

> As mentioned in a few places, I'm working on a VBA package manager written in python that strongly encourages the use of addins (Access & Excel only) as the default way to share and distribute libraries (and makes constructing them much easier). I have no idea what the repercussions of this will be, as I have relatively little experience with actual large scale VBA development and nobody seems to have an addin based network of libraries, perhaps VBE will have some arbitrary limit I am not yet aware of. Do you have any thoughts on that?

Sorry, I have no idea if there is any limit. As long as distribution of multiple files is not a problem, like in my case, then I see no issue and wish you luck in developing this project.

> I don't think there's something like #ifndef to avoid repeat declarations within the same project unfortunately.

Yes, already looked into that. Unfortunate.

Thank you for your replies!

**Comment by cristianbuse** [comment]
@Greedquest

Apologies for taking so long to act on your suggestion. I implemented the trick as I'm revisiting the repo for something else.

Thank you!

**Comment by Greedquest** [comment]
Hey, thanks for the update! Yeah looks much cleaner now. You know this repo would be a perfect candidate to test my new package manager on. Would you be interested in that (it's still a way off)? Basically it provides a way to turn your source code (.bas, .cls) into a Excel Addin automatically, and mark different versions of this repo as releases of your "package". The end user can run an update command to clone this repo and re-compile the addin (xlam) with the latest source code, so their local copy is always up-to-date. Maybe I can submit a PR down the line to add the necessary metadata if you were interested. The vision is to have an easier way to share code (although I know for your personal use-case where the client receives a single file that this isn't super useful (I have ideas on this though), it will help other users of your code.)

**Comment by Greedquest** [comment]
Actually, I can explain this a bit better by opening an issue at some point, outlining exactly what commitment is involved (hopefully basically none).

**Comment by cristianbuse** [comment]
@Greedquest Thanks! I would be happy to test your package manager!

At the end of the day, there would still be an option to simply download the latest .bas module. So, the way I see it, your manager would just be an extra option which could benefit some users.

>Actually, I can explain this a bit better by opening an issue at some point, outlining exactly what commitment is involved (hopefully basically none).

Great, will speak/chat more then.

**Comment by DecimalTurn** [comment]
While searching for VBA code on GitHub, I found this repo https://github.com/OlimilO1402/XL_VBanywhere that mentions this Enum technique and it was introduced in this [commit](https://github.com/OlimilO1402/XL_VBanywhere/commit/15abfcad7e1a9e8906054e9c2e64a99b9d94d011) from August 2021. 
@Greedquest, could that be where you saw it first?

**Comment by Greedquest** [comment]
@DecimalTurn I don't remember seeing it anywhere specific, I came up with it while I was pushing the language experimenting using enums in unusual ways such as hresults in api declares and then thinking what else you could do with them. But then when I had done it I thought "have I seen this before? Not sure". When you're doing this kind of experimental research you often end up down every corner of the internet with a hundred tabs open 😂

I don't _think_ I've seen that particular repo before although I wish I had it's a good write-up. I find you often only stumble across the perfect resource after you've learnt everything in it the hard way, probably wrong search terms...

**Comment by DecimalTurn** [comment]
I see. I guess I'll add that to the list of inventions that were made independently by a guy from the UK and another one from Germany. So far, I only had Newton and Leibniz on that list, so you're in good company 😅.
