### ISSUE TITLE
CCUR function min max values and regional settings for separators

### ISSUE THREAD

**Issue by Faxe-Riegel** [cristianbuse/VBA-MemoryTools#7]
Hello folks,
Just in case someone trips over the same issue.
Seems for my excel version (365) the min max values of the currency data type are a bit smaller than in the test module. I also did not get the separators to work for my regional settings, so I changed to relevant lines to the below:

c = CCur("-922337203685477.5625")

c = CCur("922337203685477.5625")

After that all worked as expected. 

Thanks for the great work, really helpful.

**Comment by cristianbuse** [comment]
Hi @Faxe-Riegel ,

Thanks for the separators tip. I will remove all commas.

According to Microsoft the [**Currency**](https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/currency-data-type) data type should be in range -922,337,203,685,477.5808 to 922,337,203,685,477.5807. I actually copy-pasted the values from there (including the commas).

I find it strange that your range is smaller. After all ```Currency``` is just a scaled integer and so I would expect that the ```LongLong``` test would not work either on your computer. Or maybe you are running on x32? Or maybe Mac?

**Comment by Faxe-Riegel** [comment]
Thanks for the quick reply. I have Excel 365 and run on a Windows X64, Dell Vostro 5620. No clue why...
