### ISSUE TITLE
MemCopy vs CopyMemory behaviour for overlapping source and destination 

### ISSUE THREAD

**Issue by Faxe-Riegel** [cristianbuse/VBA-MemoryTools#8]
Hello Christian,

Sorry me again. I replaced all my CopyMemory with MemCopy calls and ran my code. Excel crashed without warning.  :-(
After some digging and testing, I realized that CopyMemory and MemCopy do not behave the same way, if memory ranges overlap. (I use CopyMemory to quickly shift elements in arrays of Longs, for example for sorting.) 

See my test code and result below.

To solve the issue, I now first copy the source elements into another array and then paste it back. It is a bit of a waste of speed and memory of course, but works fine (and has acceptable speed)!!

Maybe you could do some trapping, or improve the CopyBytes function to allow for overlapping ranges ;-)? Do you have another idea how I could shift elements in a dynamic array of longs?

'*********************************************************************************************
Sub test()
Dim pArr() As Long
Dim sArr() As Long
Dim i As Byte
Dim p As Byte
Dim n As Byte

ReDim Preserve pArr(6)
ReDim Preserve sArr(6)
p = 3 'insertion point of array (where destination starts)
n = 4 'number of array elements to copy

Debug.Print String(23, "-") & "Before" & String(23, "-")
For i = 1 To 6
    pArr(i) = i
    Debug.Print "pArr(" & i & ")=" & pArr(i)
Next i
'just to initialize API (and store original values)
MemCopy VarPtr(sArr(1)), VarPtr(pArr(1)), 6 * 4

'test
Debug.Print Chr(13) & Chr(10) & "Copying first" & n & " array elements starting at position " & p & " with CopyMemory"
CopyMemory ByVal VarPtr(pArr(p)), ByVal VarPtr(pArr(1)), n * 4
For i = 1 To 6
    Debug.Print "pArr(" & i & ")=" & pArr(i)
Next i

pArr = sArr 'reset array
Debug.Print Chr(13) & Chr(10) & "Copying first" & n & " array elements starting at position " & p & " with MemCopy"
MemCopy VarPtr(pArr(p)), VarPtr(pArr(1)), n * 4
For i = 1 To 6
    Debug.Print "pArr(" & i & ")=" & pArr(i)
Next i

End Sub
'*********************************************************************************************

Result:
-----------------------Before-----------------------
pArr(1)=1
pArr(2)=2
pArr(3)=3
pArr(4)=4
pArr(5)=5
pArr(6)=6

Copying first 4 array elements starting at position 3 with CopyMemory
pArr(1)=1
pArr(2)=2
pArr(3)=1
pArr(4)=2
pArr(5)=3
pArr(6)=4

Copying first 4 array elements starting at position 3 with MemCopy
pArr(1)=1
pArr(2)=2
pArr(3)=1
pArr(4)=2
pArr(5)=12  (not correct)
pArr(6)=4

**Comment by cristianbuse** [comment]
HI @Faxe-Riegel ,

Thanks for the feedback!

> Maybe you could do some trapping, or improve the CopyBytes function to allow for overlapping ranges ;-)? Do you have another idea how I could shift elements in a dynamic array of longs?

I definitely will update the functionality to work with overlapping ranges. I hope I will find the time to do so either this week or the next. I have an idea on shifting Longs but I will have to test the idea to see if it's viable.

Will update you here once I do any update.

**Comment by cristianbuse** [comment]
Hi @Faxe-Riegel ,

I've updated the repository and it should now work fine with overlapping memory.
The idea I had for shifting Longs is much slower than ```MemCopy``` so I did not implement it.

**Comment by Faxe-Riegel** [comment]
Prefect, works like a charm. Thanks a lot for the help.
