### ISSUE TITLE
MemCopy BUG: App crashes printing results of copying 2D Variant Array 

### ISSUE THREAD

**Issue by Theadd** [cristianbuse/VBA-MemoryTools#9]
Hi there, I keep getting a whole app crash while using MemCopy from a 2D Variant Array to a 2D Variant Array.
_(Windows 11 64-bit, MS Access 2016)_

**Steps to reproduce:** _(Also attached this *.accdb in ZIP at the end of this post)_ 
* Create a new MS Access application
* Import LibMemory.bas
* Create a new module and paste the following code:
```vb
Public Sub TestCodeMemCopy()
    Dim t() As Variant, t2() As Variant
    ReDim t(0 To 5, 0 To 3)
    
    t(0, 0) = 0:    t(0, 1) = 300:  t(0, 2) = "ZERO":   t(0, 3) = 130
    t(1, 0) = -1:   t(1, 1) = 310:  t(1, 2) = "ONE":    t(1, 3) = 131
    t(2, 0) = 2:    t(2, 1) = 320:  t(2, 2) = "TWO":    t(2, 3) = 132
    t(3, 0) = -3:   t(3, 1) = 330:  t(3, 2) = "THREE":  t(3, 3) = 133
    t(4, 0) = 4:    t(4, 1) = 340:  t(4, 2) = "FOUR":   t(4, 3) = 134
    t(5, 0) = -5:   t(5, 1) = 350:  t(5, 2) = "FIVE":   t(5, 3) = 135

    ReDim t2(0 To 5, 0 To 3)
    MemCopy VBA.VarPtr(t2(0, 0)), VBA.VarPtr(t(0, 0)), VARIANT_SIZE * (6 * 4)

    Debug.Print Array2dToString(t2)
End Sub

Private Function Array2dToString(ByRef t As Variant) As String
    Dim i As Long, c As Long, r As String
    
    For i = 0 To UBound(t, 1)
        r = vbNullString
        For c = 0 To UBound(t, 2)
            r = r & vbTab & CStr(t(i, c))
        Next c
        Array2dToString = Array2dToString & VBA.Mid$(r, 2, Len(r)) & vbNewLine
    Next i
End Function
```
* Execute `TestCodeMemCopy` in the **Immediate Window**.

It doesn't crash if the string column is not included in the copy or, the `Debug.Print` line is commented (which isn't the source of the crash).

Thank you!

[TEST_LibMemory.zip](https://github.com/cristianbuse/VBA-MemoryTools/files/12489496/TEST_LibMemory.zip)

**Comment by Theadd** [comment]
Well, I found out about the "deallocating an already deallocated memory stuff" originated after an in-memory copy of an array containing either object references or BSTR, which doesn't increase their reference count, causing an extra deallocation.

Also, I've seen that you already dealt with this in your `FixByValElements()` utility which with a few changes I already got it working (so far, time will tell) for 2d arrays, moving out the ReDim and MemCopy out of `CloneParamArray()` as I'm using it for rebuilding 2d arrays from array slices.

I'm wondering if there's a more straightforward way to accomplish this without having to alter the code in LibMemory.bas

Thanks anyway, issue closed. =)

**Comment by cristianbuse** [comment]
Hi @Theadd ,

I have not been able to access a computer in the last few weeks hence responding just now.

Glad you figured the issue. Indeed when copying memory, you must always think about deallocation of unmanaged strings, arrays and objects and any nesting of these inside other arrays, objects or UDTs.

I was actually thinking a few months ago to improve the slicing of arrays in my own [array repository](https://github.com/cristianbuse/VBA-ArrayTools) which only does brute force copies, so I have a pretty good idea of what needs to be done but haven't been able to find the time to write the code.

As you probably already know, arrays are stored column-wise in VBA and so you can easily slice entire adjacent columns (either by copying memory or using a fake array trick with the latter being way faster)  but things get more difficut when you want to slice partial columns or non adjacent columns. Of course we are only speaking about 2D arrays here as anything else gets more complicated.

If you can expand on what exactly you are trying to achieve, with examples, then I will think of a tailored solution and let you know. I can always push a new function to the library if needed.

Thanks!

**Comment by Theadd** [comment]
> If you can expand on what exactly you are trying to achieve, with examples, then I will think of a tailored solution and let you know. I can always push a new function to the library if needed.

Hi again @cristianbuse and thanks for your reply,

I've just made the repository public, so you can directly get to those examples using real code.

Current implementation is as follows:

* An `ArraySliceGroup` represents a 2D collection, internally storing a 1D array of `ArraySlice`s, each one representing a **column**.
* The `ArraySlice` class represents a single **column** that can be composed of many data slices. Where each "data slice" points to a **range of rows in a single column** of an object holding the actual data, in other words, a plain array containing:
  - A reference to an object holding the _actual data_
  - The row index to start slicing
  - The count of elements to slice
  - The column index to slice from
* `ArraySliceGroup`, `ArraySlice` and the referenced objects holding the _actual data_ are **immutable** objects.
* Slicing never duplicates the "actual data", keeping a single source of truth.

The approach I was talking about in my last comment ended up in total [failure](https://github.com/Theadd/ds3x/blob/8cc6d3f63928dbe137c9ed719652daf5cc37b5df/src/ds3x.accdb.src/modules/MemoryLib.cls#L967-L1010). I got it to stop crashing, but data was inconsistent (duplicated strings), so I commented it out. 
My current implementation is just using a single call to `CloneParamArray` to [get a range of rows in a single column to a 1D array and iterate it to manually copy those values](https://github.com/Theadd/ds3x/blob/8cc6d3f63928dbe137c9ed719652daf5cc37b5df/src/ds3x.accdb.src/modules/ArraySlice.cls#L180-L183) at their respective positions within a single column 2D Array in order to reconstruct the data slices of an ArraySlice. Which is being [called (on its respective instance) for each column in an `ArraySliceGroup` and again, iterated, to manually copy those single-column 2D arrays](https://github.com/Theadd/ds3x/blob/8cc6d3f63928dbe137c9ed719652daf5cc37b5df/src/ds3x.accdb.src/modules/ArraySliceGroup.cls#L239-L244) to the final **n-columns** 2D Array.

This approach is performing extremely well compared to directly iterating to manually copy the values to a 2D Array on large data sets, but not enough. Reconstructing the same-size slices (100 rows * 16 columns):
  * __(T2)__ From 12 (+4 blank) different single-column 2D Arrays with 100 rows (generated on-the-fly by `ADODB.Recordset.GetRows` while scrolling the viewport), it takes around **0.005s**.
  * __(DS2)__ From 12 (+4 blank) different single-column 2D Arrays with 100.000 rows each, it takes around **0.160s**.
  * __(DS1)__ From a <u>single 2D Array with 100.000 rows * 12 columns</u> (+ 4 blank slices) takes around **2.000s**.
The performance dropdown comes from the `CloneParamArray` call as the number of iterations to manually copy the data are always the same (for 100rows*16columns).
_If you'd like to reproduce this test, I've attached it as [ds3x-samples.zip](https://github.com/Theadd/ds3x/releases/tag/v1.0.0-rc2), open the **DS_LIVE_EDITOR** form in **ds3x.accdb**, click the <kbd>[OPEN]</kbd> button and select the file at `.\Tasks\customers100k.json`, once loaded, each task is built the first time you click on them (from the list on the right side panel), then select the respective task (T2, DS2 or DS1) from the list and go a little bit crazy while scrolling by dragging the scrollbar thumb to see those time values printed on the immediate window._ 

![ds3x-samples-customers100k](https://github.com/cristianbuse/VBA-MemoryTools/assets/78041/dae8fb92-2df9-41ec-af57-cf1ff24037a8)

Quoting you again:
> As you probably already know, arrays are stored column-wise in VBA and so you can easily slice entire adjacent columns (either by copying memory or using a fake array trick with the latter being way faster)

Is it possible to adapt your fake array trick to get a slice of a single column, not an entire one, in a way that performs faster than using your `CloneParamArray` utility? Or, even better (I think so), is there a way to just get a variant array (can be 1D) referencing (starting at) a specific position within a 2D array? (I'll have to iterate it anyway to manually copy the values in their respective positions in the single-column 2D array, so there'd be no need to mem-copy it first.)
Otherwise, do you think of any other better approach?

Any suggestions would be very much appreciated. Thank you! =)

**Comment by cristianbuse** [comment]
Hi @Theadd ,

Apologies for the late reply - I'm super busy until mid next week.

>Is it possible to adapt your fake array trick to get a slice of a single column, not an entire one, in a way that performs faster than using your CloneParamArray utility? Or, even better (I think so), is there a way to just get a variant array (can be 1D) referencing (starting at) a specific position within a 2D array?

That is precisely what I meant by "fake array". For example, using a ```SAFEARRAY_1D``` structure we can redirect a temporary 1D array to any memory address where we have read rights, like [here](https://github.com/cristianbuse/VBA-MemoryTools/blob/922a64c48e7e6c276c7be64605216173cc8bf7d9/src/LibMemory.bas#L804-L817). So, we can point to a part column easily within 2D array. Actually, it's possible to use the same fake array to jump to different addresses and sizes in the same function call. *Deleted a phrase here, as I don't think I was correct - just ignore my previous edit*.

However, I will need to look into your repo and understand how immutability can be preserved while using such a solution while tailoring for your specific objects.

I hope to get to look into this next week or the week after at the latest.

**Comment by cristianbuse** [comment]
Hi @Theadd ,

Had a chance to quickly look over the sample files and I found that ```CloneParamArray``` is not the issue.

Just replace the line:  
```VBA
MemoryLib.CloneParamArray a2dX.Instance(v(2), v(1)), v(3), t
```
with:  
```VBA
Dim x: x = a2dX.Instance(v(2), v(1))
MemoryLib.CloneParamArray a2dX.Instance(v(2), v(1)), v(3), t
```
and you will see that the execution time gets doubled for DS1. The issue is accessing ```a2dX.Instance(v(2), v(1))```

***

The declaration ```Public Instance As Variant``` inside the Array2dEx class implies that VB creates a getter and a setter in the background, without you knowing. So, whenever you access ```Array2dEx.Instance``` you get back a copy of the array each time.

To prove the above, add this method to your Array2dEx class:
```VBA
Public Sub CloneArray(ByVal rowIndex As Long _
                    , ByVal colIndex As Long _
                    , ByVal elemCount As Long _
                    , ByRef outArray() As Variant)
    MemoryLib.CloneParamArray Instance(rowIndex, colIndex), elemCount, outArray
End Sub
````
and then replace the line in ```SliceArray``` function:
```VBA
MemoryLib.CloneParamArray a2dX.Instance(v(2), v(1)), v(3), t
```
with:
```
a2dX.CloneArray v(2), v(1), v(3), t
```
while removing the ```Dim x: x = a2dX.Instance(v(2), v(1))``` of course.

You will see that the slice is no longer 2 seconds but 0.

***

For clarity, you always want to write the accessors yourself rather than let VB do it for you. So, having a public class member is never needed plus this violates encapsulation.

It would be nice if you could activate the Discussions section of your repo but I can always use the Issues section anyway. Will probably start a few discussions/issues in the weeks to come. There are lots of ideas that came to mind while browsing through the code base and maybe we can brainstorm a few.

**Comment by Theadd** [comment]
Hi @cristianbuse 

> The declaration `Public Instance As Variant` inside the Array2dEx class implies that VB creates a getter and a setter in the background, without you knowing. So, whenever you access `Array2dEx.Instance` you get back a copy of the array each time.

You are such a genius! Really well seen with that little knowledge of how everything is implemented.

I initially chose to encapsulate the variant array in a variant variable to avoid breaking immutability unintentionally. Which is ok, but that caveat didn't came across to me, I'll keep that in mind from now on.

I'm currently adapting the code to take advantage of your `CloneArray()` approach as much as possible.

> It would be nice if you could activate the Discussions section of your repo

I have enabled them but I had never used them before, I added you as a collaborator so you can start it yourself, better than what I have done.

I am very grateful to you, thanks!

**Comment by cristianbuse** [comment]
Hi @Theadd ,

Thank you for the kind words!

> I'm currently adapting the code to take advantage of your CloneArray() approach as much as possible.

Once I have some proper time, I will push some code to move away entirely from ```CloneParamArray``` which is inneficient for your needs. As mentioned before, with fake arrays you will be able to copy array slices in one go.

> I have enabled them but I had never used them before, I added you as a collaborator so you can start it yourself, better than what I have done.

Well, thank you, but there is really no need for me to have this kind of access. I can open a discussion or issue just fine even without such permissions. Also, I can always do a pull request to add code, which of course you first review and then accept/decline/edit as needed - again all without any special access. My suggestion would be to cancel the invitation and if there's a need for such access in the future we can do it then. For now, I will try to get somewhat involved as time allows but I can't know with certainty that I will be able to dedicate time - meaning I might just point you in the right direction if I can't do it myself.

Speak soon, cheers!
